version: '3.7'

services:
  database:
    build: ./database
    container_name: todo-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todoapp

  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: todo-frontend
    ports:
      - "8080:80"
